minimumReleaseAge: 1440
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43830
strictPeerDependencies: true
packages:
  - 'packages/*'
  - playground
minimumReleaseAgeExclude:
  # Renovate security update: lodash@4.17.23
  - lodash@4.17.23
